apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  sources:
    - repoURL: https://github.com/2FromField/Gazolina.git
      targetRevision: main
      path: uv_gazolina/gitops/helm/airflow # <= le dossier ci-dessus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
