apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  # Multi-source (chart officiel + tes values dans ton repo)
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.15.0
    - repoURL: git@github.com:2FromField/Gazolina.git
      targetRevision: main
      path: gitops/helm/airflow
      ref: values
  sourcesHelm:
    valueFiles:
      - $values/values.yaml # ← chemin vers la ref
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
