# uv_gazolina/gitops/apps/postgresql.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.38
    helm:
      releaseName: postgresql
      values: |
        image:
          registry: docker.io
          repository: bitnami/postgresql
          tag: ""
          digest: "bfd6cabc00ee0712dd55ac4e9e9c21b62996492fc48ec45485a92af75b1e6709"
        primary:
          persistence:
            enabled: true
            size: 10Gi
            storageClass: "standard"
        auth:
          username: airflow
          password: airflow
          database: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # <— essentiel ici
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - Replace=true
