apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # ignoré pour ton Secret car tu as metadata.namespace: airflow
  source:
    repoURL: https://github.com/2FromField/Gazolina.git
    targetRevision: main
    path: uv_gazolina/gitops/secrets
    plugin:
      name: sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
