airflow:
  executor: LocalExecutor
  loadExamples: false

  data:
    metadataConnection:
      user: airflow
      pass: airflow
      protocol: postgresql
      host: postgresql.database.svc.cluster.local
      port: 5432
      db: airflow

  # 1) mapping des secrets (ok)
  secrets:
    - envName: AIRFLOW__CORE__FERNET_KEY
      secretName: airflow-fernet-key
      secretKey: airflow-fernet-key
    - envName: AIRFLOW__WEBSERVER__SECRET_KEY
      secretName: airflow-webserver-secret-key
      secretKey: webserver-secret-key

  # 2) injection globale (compatible schema) : impose la même clé partout
  extraEnv:
    - name: AIRFLOW__WEBSERVER__SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: airflow-webserver-secret-key
          key: webserver-secret-key

  webserver:
    defaultUser:
      enabled: true
      username: admin
      password: "change-me"
      role: Admin
      email: admin@example.com
      firstName: Admin
      lastName: User
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    service:
      type: NodePort
      ports:
        - name: http
          port: 8080
          targetPort: 8080
          nodePort: 30080

  dags:
    persistence:
      enabled: false
    gitSync:
      enabled: true
      repo: "https://github.com/2FromField/Gazolina.git"
      branch: "main"
      subPath: "uv_gazolina"
      wait: 150
      depth: 1

  scheduler:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

  triggerer:
    enabled: false

  migrateDatabaseJob:
    enabled: true

  rbac:
    create: true
  serviceAccount:
    create: true
    automountServiceAccountToken: true

  postgresql:
    enabled: false
