# ----- Exécuteur -----
executor: KubernetesExecutor
loadExamples: false

# ----- Airflow Web (exposition, optionnel) -----
service:
  type: NodePort
  ports:
    http: 8080
  nodePorts:
    http: 30080

# ----- NE PAS déployer la DB embarquée -----
postgresql:
  enabled: false

# ----- Utiliser la DB PostgreSQL déployée par Argo CD -----
# Remplace 'host' par le nom réel du Service PostgreSQL
externalDatabase:
  host: postgresql-primary.database.svc.cluster.local # <-- à ajuster (voir note ci-dessous)
  port: 5432
  user: airflow
  database: airflow
  password: "airflow" # en prod: préfère externalDatabase.existingSecret

# ----- Redis -----
# Inutile avec KubernetesExecutor (uniquement pour Celery).
redis:
  enabled: false

# ----- (Option) utilisateur web par défaut -----
auth:
  username: admin
  password: "password"
