# Toutes les clés ci-dessous ciblent le chart "airflow" (dépendance)
airflow:
  # ----- Executor -----
  executor: KubernetesExecutor
  loadExamples: false

  # ----- DB externe (postgres déployé à part via Argo CD) -----
  postgresql:
    enabled: false

  # Clés spécifiques au chart officiel Apache Airflow
  data:
    metadataConnection:
      user: airflow
      pass: airflow
      protocol: postgresql
      host: postgresql.database.svc.cluster.local # <-- ajuste si besoin (kubectl -n database get svc)
      port: 5432
      db: airflow

  # ----- RBAC + SA (KubernetesExecutor a besoin de créer des pods) -----
  rbac:
    create: true
  serviceAccount:
    create: true
    automountServiceAccountToken: true

  # ----- UI (exposée en NodePort pour test) -----
  service:
    type: NodePort
    ports:
      http: 8080
    nodePorts:
      http: 30080

  # ----- (Optionnel) GIT Sync des DAGs -----
  # Le chart officiel propose git-sync via 'dags.gitSync'
  # Dé-commente si tu veux tirer tes DAGs depuis GitHub (clé à fournir séparément).
  dags:
    persistence:
      enabled: false
    gitSync:
      enabled: true
      repo: "https://github.com/2FromField/Gazolina.git"
      branch: "main"
      subPath: "uv_gazolina/dags"
      wait: 30

  # ----- (Optionnel) Utilisateur admin (démarrage) -----
  # Pour débuter simplement (à sécuriser ensuite via Secret)
  users:
    - username: admin
      role: Admin
      email: admin@example.com
      firstName: Admin
      lastName: User
      password: "change-me"

  # (Autres overrides possibles du chart officiel ici si besoin)
