# ----- Executor -----
executor: KubernetesExecutor
loadExamples: false

# ----- UI -----
service:
  type: NodePort
  ports:
    http: 8080
  nodePorts:
    http: 30080

# ----- Pas de DB embarquée -----
postgresql:
  enabled: false

# ----- DB externe (Bitnami Postgres déployé via Argo CD) -----
externalDatabase:
  host: postgresql.database.svc.cluster.local # <= adapte si ton Service s'appelle autrement
  port: 5432
  user: airflow
  database: airflow
  password: "airflow" # prod: externalDatabase.existingSecret

# ----- Redis inutile en KubernetesExecutor -----
redis:
  enabled: false

# ----- Auth basique (à sécuriser ensuite) -----
auth:
  username: admin
  password: "password"

# ----- RBAC + SA pour KubernetesExecutor -----
rbac:
  create: true
serviceAccount:
  create: true
  automountServiceAccountToken: true

# ----- (Optionnel) Git sync des DAGs -----
git:
  dags:
    enabled: true
    repositories:
      - repository: "ssh://git@github.com/2FromField/Gazolina.git"
        branch: "main"
        name: "gazolina-dags"
        path: "uv_gazolina/dags"
  sync:
    interval: 30

# ----- (Optionnel) Pod template des workers -----
worker:
  podTemplate:
    spec:
      restartPolicy: Never
      containers:
        - name: base
          image: bitnami/airflow-worker:2.9.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
