# airflow-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.15.0 # adapte si besoin
    helm:
      values: |
        executor: KubernetesExecutor
        # Base de données : Postgres embarqué (bien pour démo). Pour prod -> Postgres managé.
        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: "16"
          auth:
            username: airflow
            password: airflow
            database: airflow

        # Git Sync: tire tes DAGs/scripts depuis GitHub en SSH
        dags:
          persistence:
            enabled: false           # simple, sans PVC; git-sync sidecar suffit
          gitSync:
            enabled: true
            repo: "ssh://git@github.com/2FromField/Gazolina.git"
            branch: "main"
            subPath: "uv_gazolina/dags"          
            wait: 30                 # pull toutes les 30s
            sshKeySecret: "airflow-ssh-secret"
            # knownHosts peut venir du secret; certains charts acceptent aussi inline:
            # knownHosts: |
            #   github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAA...

        # Expose l'UI (NodePort simple pour tester; mets un Ingress en prod)
        web:
          service:
            type: NodePort
            ports:
              - name: airflow-ui
                port: 8080
                targetPort: 8080
                nodePort: 30080

        # désactive les exemples
        airflow:
          legacyCommands: false
          config:
            core:
              load_examples: "False"
          users:
            - username: admin
              role: Admin
              email: admin@example.com
              firstName: Admin
              lastName: User
              password: "change-me"  # change-le vite (ou mets-le via Secret)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
