apiVersion: ENC[AES256_GCM,data:9OA=,iv:VZWic4i4SceqTEZrt4Zqm3MH9lHiyXHwNi+DVWfVL8Y=,tag:lo6DhoTfE/jDMcxE1kcTtw==,type:str]
kind: ENC[AES256_GCM,data:9+aHalNV,iv:CJ2IVaqzDzkxj3O8+KBLmiU3BC8VdBhPUSOKBki1DhE=,tag:JC169TvlZuBGv9RSFwwfUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NaR8qTOYyXMgOZJc6PY=,iv:ZHyBNLcM/Et94Dm0OnsNdKbADw+UXwxd4IXPVVkIII4=,tag:ILVNl2ZnUFNeliZDJzsWxA==,type:str]
    namespace: ENC[AES256_GCM,data:p2tZlsu21A==,iv:485WmPx35D3E4ucRTkCEbtc2PUZqRA0NG6NYstFfC/8=,tag:mmSd4FI1AK9fqGyp+1Q22Q==,type:str]
type: ENC[AES256_GCM,data:3Ka5GHIC,iv:Mb8IF8GLTfPUpr0jfeqhmwseAs79gn5si5jEIB84sWY=,tag:xtmKeG8iWn7sSR29/Q6Qqg==,type:str]
stringData:
    MONGO_URI: ENC[AES256_GCM,data:SEwBivbQoGv8yXJ3xSvqOfB3nTh9aCnNnJ17bPetkDQ8Vt8DGg9vn+EPgvQ14FbjHWvr2kPXR51fde/2obU9rS0+Z33m7eAHjjrT5etowrcjhms9Hs4RCsY=,iv:l9gMxCOpqFRXCbPAQ3LY6ObzXSjF88BnjbH9d7lD6Jo=,tag:C/1722CLyzpRzFuK6LVKRw==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:vN50wJeKd1mBoERxBpIKHcwZ33NU,iv:F7+PYdWRZ/eKi68kLhDjiVjE5Q1z2uay9SWV2KabGSM=,tag:4Q/PRLOAZpNUm9FFd80veA==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:Yt/w78LHIqLopoT17rPheQ==,iv:257BWqUb6ldHDOLDcJFCKHw5ffXstzZyfjerODch5Nw=,tag:KkxDlldP2qE3s+Guv/AkEA==,type:str]
sops:
    age:
        - recipient: age14f83ca3709suammnjegl60hm2ssylaq5fffd933xvxxzpx3sguxqhlh3pj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOUhKR1JxUGgrZW1Fd3Br
            b3lJYVBHOEN1UUxJYWtsRlE2VEZwczU5QjFNCjRDT1R4Mmo4VlU4ZnVDLzRjMmVH
            VTd4aHkvZXJFN1g1bmoyUGVPREJkZXMKLS0tIHBJZ0owbjZBTU92aS9XeEdjM1hm
            eTk1cVNseGg4WnNYZ0wrVmgyQUtvc2MKdQ7+/YlrZ3ddBITShuy5fm5Q44Qoijiy
            gbFf6rRqAPM01fnsoEk1t97u4NwxUmkYWtVX27UrC4WIgNkD1m5vHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T10:49:41Z"
    mac: ENC[AES256_GCM,data:48QRAvVNp6/V8K3j+7WvmNIHsxrxixV3w0yKlbVmvJ3b0ZE5LJ6uT0WEL2QL6PlUPuem8YdMu+TzHAzAoSmwOV1Oe9HPayWERgVkLEuFI/e8VMGl5jZOA2U/6EZz1z07K0C7jCBstVtsEKewWsbCgF0RxLFbgWQijNkymQrcFXs=,iv:GwswjDgdvA1x1kswTvnB4nA8/LNKrZtXBhakmyCU9nE=,tag:KBgO6tSwT783VekAIHecZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
