apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: "Plateforme data (Airflow, etc.)"
  sourceRepos:
    - "https://airflow.apache.org" # chart Helm officiel
    - "git@github.com:2FromField/Gazolina.git" # ton repo GitOps (si privé en SSH)
  destinations:
    - namespace: "airflow"
      server: "https://kubernetes.default.svc"
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
